### ISSUE TITLE
Do not treat warnings as hard errors

### ISSUE THREAD

**Issue by nene** [ga2mer/atom-lebab#4]
While working on #3 I discovered that it's quite a nuisance that having warnings completely stops Atom-Lebab from working.

I think a better approach would be to show warnings, but still apply the changes.

Even better would be to show the warnings as a clickable list (like the ESLint plugin does) so one could easily jump into the location in code and fix the warning.

**Comment by ga2mer** [comment]
> show warnings, but still apply the changes.

Released as option in 0.2.0

> Even better would be to show the warnings as a clickable list (like the ESLint plugin does) so one could easily jump into the location in code and fix the warning.

I'll think about it

**Comment by nene** [comment]
Yeah, that's better. There's also one bug:

Line numbers of warnings are wrong when I apply lebab to a selection. Lebab will count the line numbers from the beginning of selection, but the plugin should map them to the actual line numbers of file.

For example:

![screen shot 2016-08-04 at 14 44 39](https://cloud.githubusercontent.com/assets/118201/17400709/0ba95b60-5a52-11e6-9ca3-aad277b63e70.png)

**Comment by ga2mer** [comment]
Not sure of the correct working, but fixed in 0.2.1

**Comment by ga2mer** [comment]
> Even better would be to show the warnings as a clickable list (like the ESLint plugin does) so one could easily jump into the location in code and fix the warning.

Released in 0.4.0
