### ISSUE TITLE
Rename from "Atom Lebab" to simply "Lebab"

### ISSUE THREAD

**Issue by nene** [ga2mer/atom-lebab#7]
The name only needs to be unique within Atom.

The plugin already has menu entries called "Lebab", would be nice to drop the word "Atom" from everywhere else as well.

http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#rename-your-package

**Comment by ga2mer** [comment]
Renamed, but now need uninstall old package(or it's dev-atom lags)

**Comment by ga2mer** [comment]
And it seems that it broke dependencies or activate

**Comment by ga2mer** [comment]
Renamed and refactor names in 0.3.1 release
